// Regenerates src/tailwindPalette.js from the installed Tailwind theme.
// Run from lexical-demo/: node scripts/gen-palette.mjs
import { readFileSync, writeFileSync } from 'node:fs';
import { createRequire } from 'node:module';
import path from 'node:path';

const require = createRequire(import.meta.url);
const themePath = path.join(path.dirname(require.resolve('tailwindcss/package.json')), 'theme.css');
const css = readFileSync(themePath, 'utf8');
const SHADES = ['50', '100', '200', '300', '400', '500', '600', '700', '800', '900', '950'];

const families = new Map();
for (const m of css.matchAll(/--color-([a-z]+)-(\d+):\s*oklch\(([^)]+)\);/g)) {
  const [, family, shade, value] = m;
  if (!families.has(family)) families.set(family, {});
  families.get(family)[shade] = value.trim();
}

const lines = [
  '// Generated by scripts/gen-palette.mjs from tailwindcss/theme.css. Do not edit by hand.',
  '// Each value is the inside of an oklch() color, one per shade in SHADES order.',
  '',
  `export const SHADES = ${JSON.stringify(SHADES)};`,
  '',
  'export const PALETTE = {',
];
for (const [family, shades] of families) {
  const row = SHADES.map((s) => shades[s]);
  if (row.some((v) => !v)) continue;
  lines.push(`  ${family}: ${JSON.stringify(row)},`);
}
lines.push('};', '');
writeFileSync(new URL('../src/tailwindPalette.js', import.meta.url), lines.join('\n'));
console.log('families:', [...families.keys()].join(' '));
