// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/htmx/compile": {
    params: {};
  };
  "/api/suggest": {
    params: {};
  };
  "/preview": {
    params: {};
  };
  "/docs/*": {
    params: {
      "*": string;
    };
  };
};

type RouteFiles = {
  "root.jsx": {
    id: "root";
    page: "/" | "/htmx/compile" | "/api/suggest" | "/preview" | "/docs/*";
  };
  "./routes/home.jsx": {
    id: "routes/home";
    page: "/";
  };
  "./routes/htmx.compile.jsx": {
    id: "routes/htmx.compile";
    page: "/htmx/compile";
  };
  "./routes/api.suggest.jsx": {
    id: "routes/api.suggest";
    page: "/api/suggest";
  };
  "./routes/preview.jsx": {
    id: "routes/preview";
    page: "/preview";
  };
  "./routes/docs.jsx": {
    id: "routes/docs";
    page: "/docs/*";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.jsx");
  "routes/home": typeof import("./app/./routes/home.jsx");
  "routes/htmx.compile": typeof import("./app/./routes/htmx.compile.jsx");
  "routes/api.suggest": typeof import("./app/./routes/api.suggest.jsx");
  "routes/preview": typeof import("./app/./routes/preview.jsx");
  "routes/docs": typeof import("./app/./routes/docs.jsx");
};